const x = "10"


try{
    x = 20
}

catch(error){
    console.log(`Erro: ${error} Algo est√° errado!`)
}